# Generated by Django 3.1 on 2021-02-08 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('elec', 'Electronics'), ('fas', 'Fashion'), ('app', 'Home and Appliances'), ('book', 'Books and Magazines')], max_length=255)),
                ('product_info', models.CharField(max_length=1054)),
                ('date_added', models.DateField(blank=True, default=1, verbose_name='date of release')),
                ('mrp', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('product_img', models.ImageField(upload_to='product_images/')),
                ('store_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
