# Generated by Django 3.1 on 2021-02-08 07:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20210208_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 7, 30, 20, 532825, tzinfo=utc), verbose_name='date of release'),
        ),
    ]
