# Generated by Django 3.1 on 2021-02-08 10:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_auto_20210208_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('elec', 'Electronics'), ('fas', 'Fashion'), ('app', 'Home and Appliances'), ('book', 'Books and Magazines')], max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 10, 20, 17, 203175, tzinfo=utc), verbose_name='date of release'),
        ),
    ]
