# Generated by Django 3.1 on 2021-02-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='area',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='buy_date',
            field=models.DateTimeField(default=None, verbose_name='date of purchase'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_name_buy',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_price_buy',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
